openapi: 3.0.0
info:
  title: 'Day Converter'
  description: An app that gets the day that the number converts to.
  version: 0.0.1
servers:
  - url: 'http://localhost:8080/'
    description: Local dev test

paths:
  '/day/{dayNumber}':
    get:
      summary: The number that gets converted into a day.
      parameters:
        - name: dayNumber
          in: path
          required: true
          description: user's day input
          schema:
            type: integer
            format: int64
            minimum: 1
            maximum: 7
      responses:
        '200':
          description: Day conversion success!
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 2
                  name:
                    type: string
                    example: Monday
        '400': 
          description: "Invalid number!"
          
            
