openapi: 3.0.0
info:
  title: 'Hello, REST'
  description: An app that says hello to the user.
  version: 0.0.1
servers:
  - url: 'http://localhost:8080/'
    description: Local dev test

paths:
  '/hello/{name}':
    get:
      summary: the path of hello with your name.
      parameters:
        - name: name
          in: path
          required: true
          description: user's name
          schema:
            type: string
      responses:
        '200':
          description: 'Success!'
          content:
            application/text:
              schema:
                type: string